ALTER TYPE "ChangeCategory" ADD VALUE IF NOT EXISTS 'COMPONENT';
ALTER TYPE "ChangeCategory" ADD VALUE IF NOT EXISTS 'CONNECTION_LINE';
ALTER TYPE "ChangeCategory" ADD VALUE IF NOT EXISTS 'LABEL';
ALTER TYPE "ChangeCategory" ADD VALUE IF NOT EXISTS 'NOTE';
